### ISSUE TITLE
Supporting further commands

### ISSUE THREAD

**Issue by ooxi** [8none1/zengge_lednetwf#4]
Thanks for the great work! Using the commands to set color does work as intended using your script.

Do you happen to know how to change brightness or chip type (from RGB to RGBW)? I tried capturing, but my capture seems to be missing packages compared to the ones you have saved.

Might you happen to know, where in the Zengge App those packages are assembled?

**Comment by 8none1** [comment]
I’m away from the office this week so I can’t be certain (I will try and confirm next week), but…

The colour is set via HSV and so brightness is an inherent property of the overall colour value.  I have previously implement a pseudo RGB with brightness by scaling the RGB values accordingly. This isn’t a great option though. Sticking with HSV for colour and brightness is the best approach I think. 

For setting the LED type, I don’t know. My device has an RGB chip and a separate WW chip. It’s probably part of the “initial packet” set up. 
Have you look at Flux LED yet? It might already support it:

https://github.com/Danielhiversen/flux_led/blob/56cf8b57abc7c1a4e372361c653c7824e4cfc052/flux_led/protocol.py#L246

**Comment by 8none1** [comment]
Possible dupe:  https://github.com/8none1/zengge_lednetwf/issues/6

**Comment by nummacway** [comment]
flux_led is for WiFi. This repository is for BLE.

**Comment by 8none1** [comment]
Readme now has details on how to change colour ordering, chip type etc:

https://github.com/8none1/zengge_lednetwf?tab=readme-ov-file#led-settings

You need to use this along side the specific responses:

https://github.com/8none1/zengge_lednetwf?tab=readme-ov-file#led-settings

It turns out that there are at least two different firmware versions out there which are subtly different.  @nummacway tipped me off about these and I've started to investigate.

> flux_led is for WiFi. This repository is for BLE.

It is, but the protocol file linked shows that a lot of the bytes are verrrrry similar to the Bluetooth ones.
